### ISSUE TITLE
Chris Clark: A/B test current-time indicator

### ISSUE THREAD

**Issue by lindamood** [nprapps/lookatthis#860]
Does removing the time and only showing the progress bar increase the rate of completion?

**Comment by TylerFisher** [comment]
There's a slight issue with A/B testing something like this.

Google Analytics allows a GA property to store 50 unique custom variables. However, those 50 values are unique to the *property*, not to the page. We used one for Barkedu and while we didn't collide with anything the data team was doing, we did take up a slot for one story.

I guess I can just use that again, since it's a similar-ish A/B test. But I wanted to bring this up before I implement it.

**Comment by lindamood** [comment]
OK. @brianboyer do you think it's worth taking up a slot to test this?

**Comment by brianboyer** [comment]
I know the least about how this stuff works. Why wouldn't we just reuse a variable?

**Comment by TylerFisher** [comment]
Because they're not exactly comparable across projects. We're testing a timecode on an audio player here, where we were testing a progress bar on a slide-based story before.

**Comment by TylerFisher** [comment]
Alternative solution: I can tie the test to the completion analytics, if we only care about this test in relation to completion.
